### ISSUE TITLE
code still at specification version 1 despite breaking changes

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-DefHash#2]
Release 1.0.13 contained backwards-incompatible changes, yet the specification version is stil `1`.

I am surprised and wonder what is the purpose of specification version if not to indication compatibility?!?

I suggest as a minimum to document what can be expected of that specification version, but preferably to have it mean that each time backwards-incompatible changes are introduced then the specification version is bumped - which means it should be bumped now.

**Comment by perlancar** [comment]
Sorry for the late response. Didn't see the notification.

You're right. I thought I had this disclaimer like in some of my other specs:

    =head1 STATUS
    
    In the 0.x series, there will probably still be incompatible syntax changes
    between revision before the spec stabilizes into 1.x series.

but I forgot that I have set DefHash to 1.x. I think I will bump the version.

**Comment by perlancar** [comment]
I've bumped DefHash to 2.0.0.
